#!/bin/sh

APPDIR=$(dirname "$0")
$APPDIR/java/bin/java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/Arduino.jar:$APPDIR/lib/ScanComponentPCB.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-amd64.jar:$APPDIR/lib/gluegen-rt-natives-linux-amd64.jar:$APPDIR/lib/mysql-connector-java-3.1.14-bin.jar:$APPDIR/lib/postgresql-9.2-1002.jdbc3.jar:$APPDIR/lib/sqlite-jdbc-3.7.2.jar:$APPDIR/lib/BezierSQLib.jar:$APPDIR/lib/opencv-245.jar:$APPDIR/lib/opencv_processing.jar:$APPDIR/lib/jna.jar:$APPDIR/lib/gstreamer-java.jar:$APPDIR/lib/video.jar:$APPDIR/lib/controlP5.jar:$APPDIR/lib/jssc.jar:$APPDIR/lib/serial.jar" ScanComponentPCB "$@"
